### ISSUE TITLE
Using js variable inside styled-jsx component

### ISSUE THREAD

**Issue by vanmik** [omardelarosa/styled-jsx-plugin-stylus#2]
When I put js variable inside `<style jsx>` component I get an error: `StyleSheet: "insertRule" accepts only strings.`

So, this works:

```
<style jsx>{`
    p
        color: blue
`}</style>
```

but this doesn't:
```
const s = `
    p
        color: blue
`
<style jsx>{s}</style>
```

Is there a way to make this work?

**Comment by omardelarosa** [comment]
To do something like that, I think you need: https://github.com/zeit/styled-jsx#keeping-css-in-separate-files

I don't think the template literal used by styled-jsx is a plain string literal.

**Comment by vanmik** [comment]
Thank you for your fast reply. 

What template literal should I use for stylus code? `css` don't work,  this code gives me same error:

```
import css from 'styled-jsx/css'

const s = css`
    p
        color: blue
`

<style jsx>{s}</style>
```

**Comment by omardelarosa** [comment]
hmm, does this work for you without the `styled-jsx-plugin-stylus` module?  I mean when you are using vanilla styled-jsx?

**Comment by vanmik** [comment]
I tried to use same code with vanilla styled-jsx and turned out this problem is not related to your plugin. Apparently you just can't declare styles variable within `render` method: https://github.com/zeit/next.js/issues/3442

So, `css` template literal actually works for stylus code. Thank you!
