### ISSUE TITLE
Error passing stylus options

### ISSUE THREAD

**Issue by weotch** [omardelarosa/styled-jsx-plugin-stylus#3]
I am trying to use your stylus options example to import a stylus file containing variable defitions before rendering.  Here is my `.babelrc`

```json
{
  "presets": [
    [
      "next/babel",
      {
        "styled-jsx/babel": {
          "plugins": [
            "styled-jsx-plugin-stylus",
            {
              use(style) {
                return style.import('assets/definitions.styl');
              }
            }
          ]
        }
      }
    ]
  ]
}
```

I am getting the following error:

> Error while parsing JSON - Expected ']' instead of '{' at line 9 column 11 of the JSON5 data.

I think that Next babel dosn't like that function in the json.  Have you gotten this functionality to work yourself?  I'm using this with Next.js.

**Comment by omardelarosa** [comment]
Hmm, could be the syntax of `{ use() { /* ... */ } }` over like `{ use: function () { /* ... */ } }` or `{ use: () => { /* ... */ } }`.

This is how im using it now:

```javascript
const beforeRender = require('./styled-jsx-before-render');

const babelConfig = {
  'presets': [
    [
    // ...
    ]
  ],
  'plugins': [
    // ... 
    [
      'styled-jsx/babel',
      {
        'optimizeForSpeed': true,
        'plugins': [
          // note the slightly different function syntax
          [ 'styled-jsx-plugin-stylus', { use: beforeRender } ]
        ],
      }
    ],
    'transform-react-jsx',
  ]
};
```

However, I am using it outside of Next.js.  I will have to try that in Next and see.  Perhaps it's a bug when used inside of Next.js.

Can you try that syntax and see if it works for you?

**Comment by weotch** [comment]
I can't a way to configure Babel in Next.js besides the .babelrc file and it appears that it doesn't support functions.  From https://babeljs.io/docs/usage/babelrc/:

> All Babel API options except the callbacks are allowed (because .babelrc files are serialized as JSON5).

Thanks for the quick reply anyway!

**Comment by omardelarosa** [comment]
Sorry, i just noticed you said `.babelrc`.  That's gotta be JSON-serializable, yeah.
